import unittest
import numpy as np
import re
from JorG.argv import options
from JorG.Masks import MaskTemplate

class TestArgv(unittest.TestCase):
    def test_input_001(self):
        INPUT="foo --incar INCAR --input POSCAR -N 3 -E Fe"
        self.currentOptions = options(*INPUT.split())
        MASK                = self.currentOptions('mask')
        OUTPUT              = self.currentOptions('output')
        INCAR               = self.currentOptions('incar')
        POSCAR              = self.currentOptions('input')
        neighbor            = self.currentOptions('neighbor')
        self.assertIsInstance(neighbor,int)
        self.assertGreater(neighbor,0)
        self.assertEqual(neighbor,3)
        self.assertIsInstance(POSCAR,str)
        self.assertEqual(POSCAR,'POSCAR')
        self.assertIsInstance(INCAR,str)
        self.assertEqual(INCAR,'INCAR')
        self.assertIsNone(OUTPUT,str)
        self.assertIsInstance(self.currentOptions('Wyckoffs'),str)
        self.assertIsInstance(MASK,str)
        self.assertIn("Fe",MASK)
        self.assertIsInstance(self.currentOptions('reference'),int)
        self.assertIsInstance(self.currentOptions('symmetry'),bool)
        self.assertIsInstance(self.currentOptions('redundant'),bool)
        self.assertIsInstance(self.currentOptions('refined'),bool)

    def test_input_002(self):
        INPUT="foo --incar INCAR --input POSCAR -N 13 -E Ni"
        self.currentOptions = options(*INPUT.split())
        MASK                = self.currentOptions('mask')
        OUTPUT              = self.currentOptions('output')
        INCAR               = self.currentOptions('incar')
        POSCAR              = self.currentOptions('input')
        neighbor            = self.currentOptions('neighbor')
        self.assertIsInstance(neighbor,int)
        self.assertGreater(neighbor,0)
        self.assertEqual(neighbor,13)
        self.assertIsInstance(POSCAR,str)
        self.assertEqual(POSCAR,'POSCAR')
        self.assertIsInstance(INCAR,str)
        self.assertEqual(INCAR,'INCAR')
        self.assertIsNone(OUTPUT,str)
        self.assertIsInstance(self.currentOptions('Wyckoffs'),str)
        self.assertIsInstance(MASK,str)
        self.assertIn("Ni",MASK)
        self.assertIsInstance(self.currentOptions('reference'),int)
        self.assertIsInstance(self.currentOptions('symmetry'),bool)
        self.assertIsInstance(self.currentOptions('redundant'),bool)
        self.assertIsInstance(self.currentOptions('refined'),bool)

    def test_input_003(self):
        INPUT="foo --incar INCAR --input POSCAR -N 3 -E Ni"
        self.currentOptions = options(*INPUT.split())
        MASK                = self.currentOptions('mask')
        OUTPUT              = self.currentOptions('output')
        INCAR               = self.currentOptions('incar')
        POSCAR              = self.currentOptions('input')
        neighbor            = self.currentOptions('neighbor')
        self.assertIsInstance(neighbor,int)
        self.assertGreater(neighbor,0)
        self.assertEqual(neighbor,3)
        self.assertIsInstance(POSCAR,str)
        self.assertEqual(POSCAR,'POSCAR')
        self.assertIsInstance(INCAR,str)
        self.assertEqual(INCAR,'INCAR')
        self.assertIsNone(OUTPUT,str)
        self.assertIsInstance(self.currentOptions('Wyckoffs'),str)
        self.assertIsInstance(MASK,str)
        self.assertIn("Ni",MASK)
        self.assertIsInstance(self.currentOptions('reference'),int)
        self.assertGreater(neighbor,0)
        self.assertIsInstance(self.currentOptions('symmetry'),bool)
        self.assertIsInstance(self.currentOptions('redundant'),bool)
        self.assertIsInstance(self.currentOptions('refined'),bool)

    def test_input_004(self):
        INPUT="foo --incar INCAR_tst1 --input POSCAR_tst1 -N 3 -E Fe"
        self.currentOptions = options(*INPUT.split())
        MASK                = self.currentOptions('mask')
        OUTPUT              = self.currentOptions('output')
        INCAR               = self.currentOptions('incar')
        POSCAR              = self.currentOptions('input')
        neighbor            = self.currentOptions('neighbor')
        self.assertIsInstance(neighbor,int)
        self.assertGreater(neighbor,0)
        self.assertEqual(neighbor,3)
        self.assertIsInstance(POSCAR,str)
        self.assertEqual(POSCAR,'POSCAR_tst1')
        self.assertIsInstance(INCAR,str)
        self.assertEqual(INCAR,'INCAR_tst1')
        self.assertIsNone(OUTPUT,str)
        self.assertIsInstance(self.currentOptions('Wyckoffs'),str)
        self.assertIsInstance(MASK,str)
        self.assertIn("Fe",MASK)
        self.assertIsInstance(self.currentOptions('reference'),int)
        self.assertGreater(neighbor,0)
        self.assertIsInstance(self.currentOptions('symmetry'),bool)
        self.assertIsInstance(self.currentOptions('redundant'),bool)
        self.assertIsInstance(self.currentOptions('refined'),bool)

    def test_input_005(self):
        INPUT="foo --symmetry -i POSCAR_Cs2F6Ni2 "
        self.currentOptions = options(*INPUT.split())
        MASK                = self.currentOptions('mask')
        OUTPUT              = self.currentOptions('output')
        INCAR               = self.currentOptions('incar')
        POSCAR              = self.currentOptions('input')
        neighbor            = self.currentOptions('neighbor')
        self.assertIsNone(neighbor)
        self.assertIsInstance(POSCAR,str)
        self.assertEqual(POSCAR,'POSCAR_Cs2F6Ni2')
        self.assertIsInstance(INCAR,str)
        self.assertIsNone(OUTPUT,str)
        self.assertIsInstance(self.currentOptions('Wyckoffs'),str)
        self.assertIsInstance(MASK,MaskTemplate)
        self.assertIsInstance(self.currentOptions('reference'),int)
        self.assertIsInstance(self.currentOptions('symmetry'),bool)
        self.assertEqual(self.currentOptions('symmetry'),True)
        self.assertIsInstance(self.currentOptions('redundant'),bool)
        self.assertIsInstance(self.currentOptions('refined'),bool)

    def test_input_006(self):
        INPUT="foo -i POSCAR_tst1 "
        self.currentOptions = options(*INPUT.split())
        MASK                = self.currentOptions('mask')
        OUTPUT              = self.currentOptions('output')
        INCAR               = self.currentOptions('incar')
        POSCAR              = self.currentOptions('input')
        neighbor            = self.currentOptions('neighbor')
        self.assertIsNone(neighbor)
        self.assertIsInstance(POSCAR,str)
        self.assertEqual(POSCAR,'POSCAR_tst1')
        self.assertIsInstance(INCAR,str)
        self.assertEqual(INCAR,'INCAR')
        self.assertIsNone(OUTPUT,str)
        self.assertIsInstance(self.currentOptions('Wyckoffs'),str)
        self.assertIsInstance(MASK,MaskTemplate)
        self.assertIn("Mn",MASK)
        self.assertIsInstance(self.currentOptions('reference'),int)
        self.assertIsInstance(self.currentOptions('symmetry'),bool)
        self.assertIsInstance(self.currentOptions('redundant'),bool)
        self.assertIsInstance(self.currentOptions('refined'),bool)

    def test_input_007(self):
        INPUT="foo --incar INCAR_tst1 --input POSCAR_tst1 -N 2 -E Fe1"
        self.currentOptions = options(*INPUT.split())
        MASK                = self.currentOptions('mask')
        OUTPUT              = self.currentOptions('output')
        INCAR               = self.currentOptions('incar')
        POSCAR              = self.currentOptions('input')
        neighbor            = self.currentOptions('neighbor')
        self.assertIsInstance(neighbor,int)
        self.assertGreater(neighbor,0)
        self.assertEqual(neighbor,2)
        self.assertIsInstance(POSCAR,str)
        self.assertEqual(POSCAR,'POSCAR_tst1')
        self.assertIsInstance(INCAR,str)
        self.assertEqual(INCAR,'INCAR_tst1')
        self.assertIsNone(OUTPUT,str)
        self.assertIsInstance(self.currentOptions('Wyckoffs'),str)
        self.assertIsInstance(MASK,str)
        self.assertIn("Fe",MASK)
        self.assertIsInstance(self.currentOptions('reference'),int)
        self.assertIsInstance(self.currentOptions('symmetry'),bool)
        self.assertIsInstance(self.currentOptions('redundant'),bool)
        self.assertIsInstance(self.currentOptions('refined'),bool)

    def test_input_008(self):
        INPUT="foo --incar _INCARs/INCAR_tst1 --input _POSCARs/POSCAR_tst1 -N 1 -E Fe1"
        self.currentOptions = options(*INPUT.split())
        MASK                = self.currentOptions('mask')
        OUTPUT              = self.currentOptions('output')
        INCAR               = self.currentOptions('incar')
        POSCAR              = self.currentOptions('input')
        neighbor            = self.currentOptions('neighbor')
        self.assertIsInstance(neighbor,int)
        self.assertGreater(neighbor,0)
        self.assertEqual(neighbor,1)
        self.assertIsInstance(POSCAR,str)
        self.assertEqual(POSCAR,'_POSCARs/POSCAR_tst1')
        self.assertIsInstance(INCAR,str)
        self.assertEqual(INCAR,'_INCARs/INCAR_tst1')
        self.assertIsNone(OUTPUT,str)
        self.assertIsInstance(self.currentOptions('Wyckoffs'),str)
        self.assertIsInstance(MASK,str)
        self.assertIn("Fe",MASK)
        self.assertIsInstance(self.currentOptions('reference'),int)
        self.assertIsInstance(self.currentOptions('symmetry'),bool)
        self.assertIsInstance(self.currentOptions('redundant'),bool)
        self.assertIsInstance(self.currentOptions('refined'),bool)

    def test_input_009(self):
        INPUT="foo --incar _INCARs/INCAR_CsNiF --input _POSCARs/POSCAR_CsNiF -N 1 -E Ni -o output/J1"
        self.currentOptions = options(*INPUT.split())
        MASK                = self.currentOptions('mask')
        OUTPUT              = self.currentOptions('output')
        INCAR               = self.currentOptions('incar')
        POSCAR              = self.currentOptions('input')
        neighbor            = self.currentOptions('neighbor')
        self.assertIsInstance(neighbor,int)
        self.assertGreater(neighbor,0)
        self.assertEqual(neighbor,1)
        self.assertIsInstance(POSCAR,str)
        self.assertEqual(POSCAR,'_POSCARs/POSCAR_CsNiF')
        self.assertIsInstance(INCAR,str)
        self.assertEqual(INCAR,'_INCARs/INCAR_CsNiF')
        self.assertIsInstance(OUTPUT,str)
        self.assertEqual(OUTPUT,'output/J1')
        self.assertIsInstance(self.currentOptions('Wyckoffs'),str)
        self.assertIsInstance(MASK,str)
        self.assertIn("Ni",MASK)
        self.assertIsInstance(self.currentOptions('reference'),int)
        self.assertIsInstance(self.currentOptions('symmetry'),bool)
        self.assertIsInstance(self.currentOptions('redundant'),bool)
        self.assertIsInstance(self.currentOptions('refined'),bool)

    def test_input_010(self):
        INPUT="foo --symmetry -i _POSCARs/POSCAR_CsNiF -I _INCARs/INCAR_CsNiF "
        self.currentOptions = options(*INPUT.split())
        MASK                = self.currentOptions('mask')
        OUTPUT              = self.currentOptions('output')
        INCAR               = self.currentOptions('incar')
        POSCAR              = self.currentOptions('input')
        neighbor            = self.currentOptions('neighbor')
        self.assertIsNone(neighbor)
        self.assertIsInstance(POSCAR,str)
        self.assertEqual(POSCAR,'_POSCARs/POSCAR_CsNiF')
        self.assertIsInstance(INCAR,str)
        self.assertEqual(INCAR,'_INCARs/INCAR_CsNiF')
        self.assertIsNone(OUTPUT,str)
        self.assertIsInstance(self.currentOptions('Wyckoffs'),str)
        self.assertIsInstance(MASK,MaskTemplate)
        self.assertIn("Fe",MASK)
        self.assertIsInstance(self.currentOptions('reference'),int)
        self.assertIsInstance(self.currentOptions('symmetry'),bool)
        self.assertEqual(self.currentOptions('symmetry'),True)
        self.assertIsInstance(self.currentOptions('redundant'),bool)
        self.assertIsInstance(self.currentOptions('refined'),bool)

    def test_input_011(self):
        INPUT="foo -i _POSCARs/POSCAR_CsNiF -I _INCARs/INCAR_CsNiF -N 6 -E Ni -o output/ASD --redundant"
        self.currentOptions = options(*INPUT.split())
        MASK                = self.currentOptions('mask')
        OUTPUT              = self.currentOptions('output')
        INCAR               = self.currentOptions('incar')
        POSCAR              = self.currentOptions('input')
        neighbor            = self.currentOptions('neighbor')
        self.assertIsInstance(neighbor,int)
        self.assertGreater(neighbor,0)
        self.assertEqual(neighbor,6)
        self.assertIsInstance(POSCAR,str)
        self.assertEqual(POSCAR,'_POSCARs/POSCAR_CsNiF')
        self.assertIsInstance(INCAR,str)
        self.assertEqual(INCAR,'_INCARs/INCAR_CsNiF')
        self.assertIsInstance(OUTPUT,str)
        self.assertEqual(OUTPUT,'output/ASD')
        self.assertIsInstance(self.currentOptions('Wyckoffs'),str)
        self.assertIsInstance(MASK,str)
        self.assertIn("Ni",MASK)
        self.assertIsInstance(self.currentOptions('reference'),int)
        self.assertIsInstance(self.currentOptions('symmetry'),bool)
        self.assertIsInstance(self.currentOptions('redundant'),bool)
        self.assertEqual(self.currentOptions('redundant'),True)
        self.assertIsInstance(self.currentOptions('refined'),bool)

    def test_input_012(self):
        INPUT="foo -i _POSCARs/POSCAR_CsNiF -I _INCARs/INCAR_CsNiF -N 2 -E Ni -o output/ASD "
        self.currentOptions = options(*INPUT.split())
        MASK                = self.currentOptions('mask')
        OUTPUT              = self.currentOptions('output')
        INCAR               = self.currentOptions('incar')
        POSCAR              = self.currentOptions('input')
        neighbor            = self.currentOptions('neighbor')
        self.assertIsInstance(neighbor,int)
        self.assertGreater(neighbor,0)
        self.assertEqual(neighbor,2)
        self.assertIsInstance(POSCAR,str)
        self.assertEqual(POSCAR,'_POSCARs/POSCAR_CsNiF')
        self.assertIsInstance(INCAR,str)
        self.assertEqual(INCAR,'_INCARs/INCAR_CsNiF')
        self.assertIsInstance(OUTPUT,str)
        self.assertEqual(OUTPUT,'output/ASD')
        self.assertIsInstance(self.currentOptions('Wyckoffs'),str)
        self.assertIsInstance(MASK,str)
        self.assertIn("Ni",MASK)
        self.assertIsInstance(self.currentOptions('reference'),int)
        self.assertIsInstance(self.currentOptions('symmetry'),bool)
        self.assertIsInstance(self.currentOptions('redundant'),bool)
        self.assertIsInstance(self.currentOptions('refined'),bool)

    def test_input_013(self):
        INPUT="foo -i _POSCARs/POSCAR_CsNiF -I _INCARs/INCAR_CsNiF -N 2 -E Ni -o output/ASD --reference 21"
        self.currentOptions = options(*INPUT.split())
        MASK                = self.currentOptions('mask')
        OUTPUT              = self.currentOptions('output')
        INCAR               = self.currentOptions('incar')
        POSCAR              = self.currentOptions('input')
        neighbor            = self.currentOptions('neighbor')
        self.assertIsInstance(neighbor,int)
        self.assertGreater(neighbor,0)
        self.assertEqual(neighbor,2)
        self.assertIsInstance(POSCAR,str)
        self.assertEqual(POSCAR,'_POSCARs/POSCAR_CsNiF')
        self.assertIsInstance(INCAR,str)
        self.assertEqual(INCAR,'_INCARs/INCAR_CsNiF')
        self.assertIsInstance(OUTPUT,str)
        self.assertEqual(OUTPUT,'output/ASD')
        self.assertIsInstance(self.currentOptions('Wyckoffs'),str)
        self.assertIsInstance(MASK,str)
        self.assertIn("Ni",MASK)
        self.assertIsInstance(self.currentOptions('reference'),int)
        self.assertEqual(self.currentOptions('reference'),21-1)
        self.assertIsInstance(self.currentOptions('symmetry'),bool)
        self.assertIsInstance(self.currentOptions('redundant'),bool)
        self.assertIsInstance(self.currentOptions('refined'),bool)

    def test_input_014(self):
        INPUT="foo -i _POSCARs/POSCAR_CsNiF -I _INCARs/INCAR_CsNiF -E Ni -o output/ASD -R 123.0"
        self.currentOptions = options(*INPUT.split())
        MASK                = self.currentOptions('mask')
        OUTPUT              = self.currentOptions('output')
        INCAR               = self.currentOptions('incar')
        POSCAR              = self.currentOptions('input')
        neighbor            = self.currentOptions('neighbor')
        self.assertIsNone(neighbor,int)
        self.assertIsInstance(self.currentOptions('cutOff'),float)
        self.assertAlmostEqual(self.currentOptions('cutOff'),123.0)
        self.assertIsInstance(POSCAR,str)
        self.assertEqual(POSCAR,'_POSCARs/POSCAR_CsNiF')
        self.assertIsInstance(INCAR,str)
        self.assertEqual(INCAR,'_INCARs/INCAR_CsNiF')
        self.assertIsInstance(OUTPUT,str)
        self.assertEqual(OUTPUT,'output/ASD')
        self.assertIsInstance(self.currentOptions('Wyckoffs'),str)
        self.assertIsInstance(MASK,str)
        self.assertIn("Ni",MASK)
        self.assertIsInstance(self.currentOptions('reference'),int)
        self.assertIsInstance(self.currentOptions('symmetry'),bool)
        self.assertIsInstance(self.currentOptions('redundant'),bool)
        self.assertIsInstance(self.currentOptions('refined'),bool)

    def test_input_015(self):
        INPUT="foo -i _POSCARs/POSCAR_CsNiF -I _INCARs/INCAR_CsNiF -N 2 -E Ni -o output/ASD --refined"
        self.currentOptions = options(*INPUT.split())
        MASK                = self.currentOptions('mask')
        OUTPUT              = self.currentOptions('output')
        INCAR               = self.currentOptions('incar')
        POSCAR              = self.currentOptions('input')
        neighbor            = self.currentOptions('neighbor')
        self.assertIsInstance(neighbor,int)
        self.assertGreater(neighbor,0)
        self.assertEqual(neighbor,2)
        self.assertIsInstance(POSCAR,str)
        self.assertEqual(POSCAR,'_POSCARs/POSCAR_CsNiF')
        self.assertIsInstance(INCAR,str)
        self.assertEqual(INCAR,'_INCARs/INCAR_CsNiF')
        self.assertIsInstance(OUTPUT,str)
        self.assertEqual(OUTPUT,'output/ASD')
        self.assertIsInstance(self.currentOptions('Wyckoffs'),str)
        self.assertIsInstance(MASK,str)
        self.assertIn("Ni",MASK)
        self.assertIsInstance(self.currentOptions('reference'),int)
        self.assertIsInstance(self.currentOptions('symmetry'),bool)
        self.assertIsInstance(self.currentOptions('redundant'),bool)
        self.assertIsInstance(self.currentOptions('refined'),bool)
        self.assertEqual(self.currentOptions('refined'),True)

    def test_input_016(self):
        INPUT="foo -i _POSCARs/POSCAR_CsNiF -I _INCARs/INCAR_CsNiF -N 2 -E Ni -o output/ASD  --period 3d 5p"
        self.currentOptions = options(*INPUT.split())
        MASK                = self.currentOptions('mask')
        OUTPUT              = self.currentOptions('output')
        INCAR               = self.currentOptions('incar')
        POSCAR              = self.currentOptions('input')
        neighbor            = self.currentOptions('neighbor')
        self.assertIsInstance(neighbor,int)
        self.assertGreater(neighbor,0)
        self.assertEqual(neighbor,2)
        self.assertIsInstance(POSCAR,str)
        self.assertEqual(POSCAR,'_POSCARs/POSCAR_CsNiF')
        self.assertIsInstance(INCAR,str)
        self.assertEqual(INCAR,'_INCARs/INCAR_CsNiF')
        self.assertIsInstance(OUTPUT,str)
        self.assertEqual(OUTPUT,'output/ASD')
        self.assertIsInstance(self.currentOptions('Wyckoffs'),str)
        self.assertIsInstance(MASK,str)
        self.assertIn("Ni",MASK)
        self.assertIn("Ti",MASK)
        self.assertIn("Mn",MASK)
        self.assertIn("Te",MASK)
        self.assertIn("In",MASK)
        self.assertIsInstance(self.currentOptions('reference'),int)
        self.assertIsInstance(self.currentOptions('symmetry'),bool)
        self.assertIsInstance(self.currentOptions('redundant'),bool)
        self.assertIsInstance(self.currentOptions('refined'),bool)

    def test_input_017(self):
        INPUT="foo -i _POSCARs/POSCAR_CsNiF -I _INCARs/INCAR_CsNiF -N 2 -E Ni -o output/ASD  --block D"
        self.currentOptions = options(*INPUT.split())
        MASK                = self.currentOptions('mask')
        OUTPUT              = self.currentOptions('output')
        INCAR               = self.currentOptions('incar')
        POSCAR              = self.currentOptions('input')
        neighbor            = self.currentOptions('neighbor')
        self.assertIsInstance(neighbor,int)
        self.assertGreater(neighbor,0)
        self.assertEqual(neighbor,2)
        self.assertIsInstance(POSCAR,str)
        self.assertEqual(POSCAR,'_POSCARs/POSCAR_CsNiF')
        self.assertIsInstance(INCAR,str)
        self.assertEqual(INCAR,'_INCARs/INCAR_CsNiF')
        self.assertIsInstance(OUTPUT,str)
        self.assertEqual(OUTPUT,'output/ASD')
        self.assertIsInstance(self.currentOptions('Wyckoffs'),str)
        self.assertIsInstance(MASK,str)
        self.assertIn("Ni",MASK)
        self.assertIn("Fe",MASK)
        self.assertIn("Au",MASK)
        self.assertIn("Hg",MASK)
        self.assertIn("Cr",MASK)
        self.assertIn("Hf",MASK)
        self.assertIsInstance(self.currentOptions('reference'),int)
        self.assertIsInstance(self.currentOptions('symmetry'),bool)
        self.assertIsInstance(self.currentOptions('redundant'),bool)
        self.assertIsInstance(self.currentOptions('refined'),bool)

    def test_input_018(self):
        INPUT="foo -i _POSCARs/POSCAR_CsNiF -I _INCARs/INCAR_CsNiF -N 2 -E Ni -o output/ASD  --group 2 5"
        self.currentOptions = options(*INPUT.split())
        MASK                = self.currentOptions('mask')
        OUTPUT              = self.currentOptions('output')
        INCAR               = self.currentOptions('incar')
        POSCAR              = self.currentOptions('input')
        neighbor            = self.currentOptions('neighbor')
        self.assertIsInstance(neighbor,int)
        self.assertGreater(neighbor,0)
        self.assertEqual(neighbor,2)
        self.assertIsInstance(POSCAR,str)
        self.assertEqual(POSCAR,'_POSCARs/POSCAR_CsNiF')
        self.assertIsInstance(INCAR,str)
        self.assertEqual(INCAR,'_INCARs/INCAR_CsNiF')
        self.assertIsInstance(OUTPUT,str)
        self.assertEqual(OUTPUT,'output/ASD')
        self.assertIsInstance(self.currentOptions('Wyckoffs'),str)
        self.assertIsInstance(MASK,str)
        self.assertIn("Ni",MASK)
        self.assertIn("Be",MASK)
        self.assertIn("Mg",MASK)
        self.assertIn("Ca",MASK)
        self.assertIn("Nb",MASK)
        self.assertIn("Ta",MASK)
        self.assertIsInstance(self.currentOptions('reference'),int)
        self.assertIsInstance(self.currentOptions('symmetry'),bool)
        self.assertIsInstance(self.currentOptions('redundant'),bool)
        self.assertIsInstance(self.currentOptions('refined'),bool)

if __name__ == '__main__':
    unittest.main()
